//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Bill_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Bill_()
        {
            this.C_Bill_Detail_ = new HashSet<C_Bill_Detail_>();
        }
    
        public string BillID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalFinal { get; set; }
        public string Payment { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Status { get; set; }
        public string OrderID { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Bill_Detail_> C_Bill_Detail_ { get; set; }
        public virtual C_Order_ C_Order_ { get; set; }
        public virtual C_User_ C_User_ { get; set; }
    }
}
