//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Recipe_Detail_
    {
        public string RecipeID { get; set; }
        public string IngreID { get; set; }
        public string UnitMeasurement { get; set; }
        public Nullable<long> Quantity { get; set; }
    
        public virtual C_Ingredient_ C_Ingredient_ { get; set; }
        public virtual C_Recipe_ C_Recipe_ { get; set; }
    }
}
