//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCNPM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLQuanAnEntities : DbContext
    {
        public QLQuanAnEntities()
            : base("name=QLQuanAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Bill_> C_Bill_ { get; set; }
        public virtual DbSet<C_Bill_Detail_> C_Bill_Detail_ { get; set; }
        public virtual DbSet<C_Category_> C_Category_ { get; set; }
        public virtual DbSet<C_Food_Info_> C_Food_Info_ { get; set; }
        public virtual DbSet<C_Ingredient_> C_Ingredient_ { get; set; }
        public virtual DbSet<C_Order_> C_Order_ { get; set; }
        public virtual DbSet<C_Order_Detail_> C_Order_Detail_ { get; set; }
        public virtual DbSet<C_Recipe_> C_Recipe_ { get; set; }
        public virtual DbSet<C_Recipe_Detail_> C_Recipe_Detail_ { get; set; }
        public virtual DbSet<C_Table_> C_Table_ { get; set; }
        public virtual DbSet<C_User_> C_User_ { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
