//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Order_()
        {
            this.C_Bill_ = new HashSet<C_Bill_>();
            this.C_Bill_Detail_ = new HashSet<C_Bill_Detail_>();
            this.C_Order_Detail_ = new HashSet<C_Order_Detail_>();
        }
    
        public string OrderID { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string TableID { get; set; }
        public string ReservationID { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Bill_> C_Bill_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Bill_Detail_> C_Bill_Detail_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Order_Detail_> C_Order_Detail_ { get; set; }
        public virtual C_Table_ C_Table_ { get; set; }
        public virtual C_User_ C_User_ { get; set; }
    }
}
